baseURL: "https://mahrokhgb.github.io"
title: Mahrokh Ghoddousi Boroujeni
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Skills
          url: skills/
          weight: 5
        - name: Experience
          url: experience/
          weight: 3
        - name: Publications
          url: publications/
          weight: 2
        # - name: Awards
        #   url: awards/
        #   weight: 4

params:
    description: "I am a PhD student at EPFL in Lausanne, Switzerland. My research focuses mostly on Machine Learning and Auotomation and Control Theory."
    author: Mahrokh Ghoddousi Boroujeni
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    # defaultTheme: light
    hideFooter: false
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","experience","skills"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mahrokh Ghoddousi Boroujeni
          subtitle: "
          I am a PhD student at EPFL in Lausanne, Switzerland,
          supervised by [Prof. Giancarlo Ferrari Trecate](https://people.epfl.ch/giancarlo.ferraritrecate)
          and co-supervised by [Prof. Andreas Krause.](https://las.inf.ethz.ch/krausea)

          My research focuses on employing advanced machine learning techniques to
          develop complex controllers for intricate tasks.

          <br><br>
          Learning models and controllers from data has become ubiquitous,
          yet it often involves *limited* and *noisy* datasets.

          I study the impact of such factors on the performance and reliability
          of learned models and controllers.

          Specifically, I aim to develop models and controllers that *generalize well*
          and *maintain stability* beyond their training data.
          I also explore the *uncertainty* in the learned model due to noise using probabilistic modeling.
          Finally, I am interested in leveraging multiple related datasets through
          *meta-learning* and *federated learning* approaches to enhance performance and robustness.


        socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:mahrokh.ghoddousiboroujeni@epfl.ch
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hE8QWWcAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/MahrokhGB
        - name: LinkedIn
          url: https://www.linkedin.com/in/mahrokhghoddousi

          <br><br>
          <hr>
          <br>

          **📚 Research interests:**<br><br>
          <table>
          <tr>
          <th>
          *Machine Learning*
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;</th>
          <th>
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          *Automation and Control* </th>
          </tr>
          <tr>
          <td>
          &ensp;• Generalization theory<br>
          &ensp;• Probabilistic models<br>
          &ensp;• Meta and transfer learning<br>
          &ensp;• Differential privacy<br>

          </td>
          <td>
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;• Stability<br>
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;• Learning-based control<br>
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;• Policy optimization<br>
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
          &ensp;• System identification<br>
          </td>
          </tr>
          </table>


          <br><br>
          <hr>
          <br>
          **🎓 Education:**<br><br>
          &ensp;• PhD, Robotics and Intelligent Systems<br>
          &ensp;&ensp;&ensp;  École Polytechnique Fédérale de Lausanne (EPFL), Switzerland<br>
          &ensp;&ensp;&ensp;  *November 2020 - Present<br>*
          &ensp;&ensp;&ensp;- Supervisor: [Prof. Giancarlo Ferrari Trecate](https://people.epfl.ch/giancarlo.ferraritrecate), DECODE, EPFL<br>
          &ensp;&ensp;&ensp;- Co-supervisor: [Prof. Andreas Krause](https://las.inf.ethz.ch/krausea), LAS, ETHZ<br>
          <br>

          &ensp;• B.Sc, Electrical Engineering, Control specialization<br>
          &ensp;&ensp;&ensp;  Sharif University of Technology, Iran<br>
          &ensp;&ensp;&ensp;  *September 2015 - July 2020*<br>
          &ensp;&ensp;&ensp;- GPA: 18.45 out of 20<br>
          &ensp;&ensp;&ensp;- Thesis: Camera-Based Real-Time Autonomous Racing Cars.
            Video processing with OpenCV and a high-performance C++ hardware interaction.
          <br>

          &ensp;• B.Sc, Computer Science<br>
          &ensp;&ensp;&ensp;  Sharif University of Technology, Iran<br>
          &ensp;&ensp;&ensp;  *September 2015 - July 2020*<br>
          <br>

          &ensp;• High School Diploma, Mathematics and Physics<br>
          &ensp;&ensp;&ensp;  Farzanegan High Schools, Iran<br>
          &ensp;&ensp;&ensp;  *September 2008 - June 2015*<br>
          &ensp;&ensp;&ensp;- Associated with the National Organization for Development of Exceptional Talents

          "
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Mahrokh Ghoddousi Boroujeni
          buttons:
            - name: Publications
              url: publications/
            - name: Experience
              url: experience/
            # - name: Awards
            #   url: awards/
            - name: Skills
              url: skills/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    # socialIcons:
    #     - name: CV
    #       url: cv.pdf
    #     - name: Email
    #       url: mailto:mahrokh.ghoddousiboroujeni@epfl.ch
    #     # - name: Zoom
    #     #   url: https://www.zoom.us/my/igelfeld
    #     # - name: Location
    #     #   url: location/
    #     # - name: Office Hours
    #     #   url: officehours/
    #     - name: Google Scholar
    #       url: https://scholar.google.com/citations?user=hE8QWWcAAAAJ&hl=en
    #     - name: GitHub
    #       url: https://github.com/MahrokhGB
    #     - name: LinkedIn
    #       url: https://www.linkedin.com/in/mahrokhghoddousi
    #     # - name: YouTube
    #     #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
    #     # - name: Twitter
    #     #   url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mahrokh Ghoddousi Boroujeni"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2